@startuml
left to right direction
entity staff {
    id
    email
    displayName
}
entity tags {
    id
    value
    label
}
entity observations {
    id : pk
    _id : mongoDB_id
    date : ISO
    observer : email
    observed : email
    type : integer
    reflection : base64 encoded HTML
    feedback : base64 encoded HTML
    recording_url : URL to zoom recording
}
entity observations_tags {
    id : pk
    email : observed - for grouping easily
    tag : slug
    observation_id : mongoDB_id
}
staff::email---{observations::observed
observations::_id---{observations_tags::observation_id
observations_tags::tag---{tags::value
@enduml